name: cs5228
dependencies:
  - python=3.10
  - pip
  - pip:
    - jupyterlab
    - jupyterlab-vim
    - numpy
    - pandas
    - scikit-learn
    - networkx
    - torch
    - tensorboard
    - matplotlib
    - seaborn
    - tqdm
    - rich
